### ISSUE TITLE
PVnet backtest analysis

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/PVNet-summation#8]
## Detailed Description
We have run a backtest for PVNet and we shoudl do some analysis on this

## Context
- good to be able to send to people, to show how good our forecast is

## Possible Implementation

Merge national all together from each init forecast

Metrics:
- MAE
- RMSE
- R2
- p10,p25,p75,p90 absolute errors using pinball score
- MBE?
- Ramp rate

We should compare 
A: `PVnet` to `PVLive update` for the whole of 2022
B:
1. `PVnet` to `PVLive update` for the whole of 2022-07-01 to 2023-01-01
2. `PVLive initial` to `PVLive update` for the whole of 2022-07-01 to 2023-01-01

**Comment by peterdudfield** [comment]
Extra
- look at different forecast horzons
- std distirbution of MAE - maybe T test
- bonus: National_xg -

**Comment by peterdudfield** [comment]
Run Pinball loss on each quantile forecast for PVnet

**Comment by dantravers** [comment]
I'd definitely like to see step 8, as it's interesting, and they are looking for seasonal / time-of-day analysis. 
For probabilistic, I would add just a simple count of exceedences. 
General principle - let's play around a bit, but then narrow down on the metrics we wish to see repeated when we do this analysis again, as I'm 100% sure we will want to re-run this in another few months as we improve PVNet2.

**Comment by dantravers** [comment]
Yep, exceedence and pinball, agreed.

**Comment by dfulu** [comment]
I'm going to close this because I think it has been completed
